# Generated by Django 3.0.3 on 2020-04-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='todo',
            new_name='todos',
        ),
    ]
